from pydantic import BaseModel
from datetime import datetime

class CreateAlunoDto(BaseModel):
    aluno: str
    sexo: str
    treinador: str
    data_nascimento: datetime
    objetivo: str
    tempo_treinamento_ininterrupto_atual: str
    tempo_destreinamento: str
    experiencia_previa_treinamento: str
    frequencia_musculacao: str
    modalidade_extra: str
    frequencia_modalidade_extra: str
    altura: float
    peso: float
    torax: float
    cintura: float
    abdomen: float
    quadril: float
    braco_d: float
    braco_e: float
    coxa_d: float
    coxa_e: float
    panturrilha_d: float
    panturrilha_e: float
    medida_mao: float
    mobilidade_glenoumeral_direita: float
    mobilidade_glenoumeral_esquerda: float
    amplitude_movimento_quadril_direito: float
    amplitude_movimento_quadril_esquerdo: float
    amplitude_movimento_tornozelo_direito: float
    amplitude_movimento_tornozelo_esquerdo: float
    prancha_ventral: float
    extensao_coluna: float
    prancha_lateral_direita: float
    prancha_lateral_esquerda: float
    squat_jump_1: float
    squat_jump_2: float
    squat_jump_3: float
    rm_agachamento: float
    rm_supino: float
    rm_terra: float
    rm_barra_fixa: float
    velocidade_aerobia_maxima: float
    braco_direito: float
    braco_esquerdo: float
    coxa_direita: float
    coxa_esquerda: float
    panturrilha_direita: float
    panturrilha_esquerda: float
    idade: int
    data: datetime
    hora: datetime
    pontuacao_tempo_treino_atual: int
    pontuacao_tempo_destreinamento_atual: int
    pontuacao_experiencia_previa_treinamento: int
    pontuacao_media_nivel_treinamento: float
    status_treinamento: str
    nivel_mob_tornozelo_direito: str
    nivel_mob_tornozelo_esquerdo: str
    nivel_mob_quadril_direito: str
    nivel_mob_quadril_esquerdo: str
    nivel_mob_ombro_direito: str
    nivel_mob_ombro_esquerdo: str
    nivel_prancha_ventral: str
    nivel_extensao_coluna: str
    nivel_prancha_lateral_direita: str
    nivel_prancha_lateral_esquerda: str
    pontos_prancha_ventral: float
    pontos_extensao_coluna: float
    pontos_prancha_lateral_direita: float
    pontos_prancha_lateral_esquerda: float
    forca_relativa_agachamento: float
    forca_relativa_supino: float
    forca_relativa_terra: float
    forca_relativa_barra_fixa: float
    squat_nivel: str
    supino_nivel: str
    terra_nivel: str
    pontuacao_squat_nivel: float
    pontuacao_supino_nivel: float
    pontuacao_terra_nivel: float
    media_squat_jump: float
    vo2_estimado: float
    faixa_etaria: str
    nivel_vo2: str
    imc: float
    classificacao_imc: str
    idtag_aluno: str
